### ISSUE TITLE
how get a good bag file？

### ISSUE THREAD

**Issue by sczgzzzj** [Livox-SDK/livox_horizon_loam#10]
Could you please tell me that I cannot get the calculation effect of the official bag when I use the bag recorded by livox_lidar_msg.launch, so do I need to set it when recording the bag? I'd like some help. Thank you

**Comment by PanZhichen** [comment]
This project is mainly used in low-speed scenes, so please move slowly (<10km / h) during the recording process. Generally, using IMU can improve the SLAM effect, so please remember to record the topic "/livox/imu" into your rosbag.

**Comment by sczgzzzj** [comment]
谢谢，已解决
