### ISSUE TITLE
Run times error

### ISSUE THREAD

**Issue by sczgzzzj** [Livox-SDK/livox_horizon_loam#2]
[ERROR] [1582104656.932088632]: Client [/livox_repub] wants topic /livox/lidar to have datatype/md5sum [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.

What's the problem, please

**Comment by mbennehar** [comment]
They use the custom cloud format, in your driver launch you need to change xfer_format from 0 to 1

**Comment by sczgzzzj** [comment]
Thank you, it's ready to use, but the test results are not so good

**Comment by mbennehar** [comment]
Try this one instead: https://github.com/hku-mars/loam_livox

**Comment by PanZhichen** [comment]
hi @sczgzzzj , if you want to run the demo directly, you need to launch the livox_ros_driver with livox_lidar_msg.launch to allow CustomMsg output. Or you can run the rosbag example, the[ download link](https://terra-1-g.djicdn.com/65c028cd298f4669a7f0e40e50ba1131/demo/parking_lot.bag) was updated recently.

**Comment by Livox-SDK** [comment]
Hi,sczgzzzj and mbennehar
    The livox_horizon_loam only support the CustomMsg format, must use livox_lidar_msg.launch to launch the livx_ros_driver.

**Comment by sczgzzzj** [comment]
tanks，I'll test it to see if it works


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"matlabbe"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月25日(星期二) 下午4:56
收件人:&nbsp;"Livox-SDK/livox_horizon_loam"<livox_horizon_loam@noreply.github.com&gt;;
抄送:&nbsp;"zzzj"<370186169@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Livox-SDK/livox_horizon_loam] Run times error (#2)




Hi,sczgzzzj and mbennehar
 The livox_horizon_loam only support the CustomMsg format, must use livox_lidar_msg.launch to launch the livx_ros_driver.
