### ISSUE TITLE
Can't calculate

### ISSUE THREAD

**Issue by sczgzzzj** [Livox-SDK/livox_horizon_loam#8]
zzzj@zzzj:~/catkin_ws$ roslaunch loam_horizon loam_livox_horizon.launch
... logging to /home/zzzj/.ros/log/fc07f920-99de-11ea-8582-c4d98799c302/roslaunch-zzzj-10137.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://zzzj:40781/

SUMMARY
========

PARAMETERS
 * /mapping_line_resolution: 0.3
 * /mapping_plane_resolution: 0.6
 * /mapping_skip_frame: 2
 * /minimum_range: 0.3
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /scan_line: 6
 * /threshold_flat: 0.01
 * /threshold_sharp: 0.1

NODES
  /
    laserMapping (loam_horizon/laserMapping)
    laserOdometry (loam_horizon/laserOdometry)
    livox_repub (loam_horizon/livox_repub)
    rviz (rviz/rviz)
    scanRegistration (loam_horizon/scanRegistration)

auto-starting new master
process[master]: started with pid [10147]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to fc07f920-99de-11ea-8582-c4d98799c302
process[rosout-1]: started with pid [10160]
started core service [/rosout]
process[scanRegistration-2]: started with pid [10172]
process[laserOdometry-3]: started with pid [10178]
process[laserMapping-4]: started with pid [10179]
process[livox_repub-5]: started with pid [10187]
Mapping 5 Hz 
process[rviz-6]: started with pid [10193]
[ INFO] [1589899358.673880559]: start livox_repub
scan line number 6 
line resolution 0.300000 plane resolution 0.600000 
points size 22605 
prepare time 5.818291 
sort q time 1.966182 
seperate points time 4.824765 
scan registration time 16.504640 ms *************
Initialization finished 
publication time 8.713276 ms 
whole laserOdometry time 8.776731 ms 
 
map prepare time 0.268825 ms
map corner num 0  surf num 0 
[ WARN] [1589899369.000657958]: time Map corner and surf num are not enough
add points time 0.064741 ms
filter time 0.503859 ms 
mapping pub time 4.369223 ms 
whole mapping time 5.561359 ms +++++
points size 22693 
prepare time 2.868194 
sort q time 2.249739 
seperate points time 4.619469 
scan registration time 11.440953 ms *************
data association time 9.276748 ms 
solver time 12.395173 ms 
data association time 10.845608 ms 
solver time 10.061607 ms 
optimization twice time 43.386836 
t_w_curr:  0.0818173 0.00438026 0.00992547
publication time 8.230904 ms 
whole laserOdometry time 51.782643 ms 
 
points size 22703 
prepare time 3.634014 
sort q time 2.274923 
seperate points time 5.093734 
scan registration time 12.782456 ms *************
data association time 7.990031 ms 
solver time 9.597534 ms 
data association time 8.046268 ms 
solver time 6.374530 ms 
optimization twice time 32.595536 
t_w_curr:   0.173467 0.00919051  0.0106125
publication time 7.973334 ms 
whole laserOdometry time 40.664500 ms 
 
[laserMapping-4] process has died [pid 10179, exit code -11, cmd /home/zzzj/catkin_ws/devel/lib/loam_horizon/laserMapping __name:=laserMapping __log:=/home/zzzj/.ros/log/fc07f920-99de-11ea-8582-c4d98799c302/laserMapping-4.log].
log file: /home/zzzj/.ros/log/fc07f920-99de-11ea-8582-c4d98799c302/laserMapping-4*.log
points size 22634 
prepare time 8.347636 
sort q time 2.019777 
seperate points time 4.798511 
scan registration time 18.234239 ms *************
data association time 7.992015 ms 
solver time 6.208782 ms 
data association time 6.530049 ms 
solver time 6.304133 ms 
optimization twice time 27.522775 
t_w_curr:   0.259279  0.0198044 0.00887386
publication time 5.349825 ms 
whole laserOdometry time 32.942995 ms 

Compile the prompt that appears：

[ 91%] Linking CXX executable /home/zzzj/catkin_ws/devel/lib/loam_horizon/laserMapping
[100%] Linking CXX executable /home/zzzj/catkin_ws/devel/lib/loam_horizon/imu_process
[100%] Built target laserOdometry
[100%] Built target imu_process
/usr/bin/ld: warning: libpcl_filters.so.1.9, needed by /usr/local/lib/libpcl_segmentation.so, may conflict with libpcl_filters.so.1.7
/usr/bin/ld: warning: libpcl_common.so.1.9, needed by /usr/local/lib/libpcl_segmentation.so, may conflict with libpcl_common.so.1.7
/usr/bin/ld: warning: libpcl_kdtree.so.1.9, needed by /usr/local/lib/libpcl_features.so, may conflict with libpcl_kdtree.so.1.7
[100%] Built target laserMapping

What's the reason, please

**Comment by PanZhichen** [comment]
This project was compiled using PCL1.7 and may conflict with PCL1.9 installed in your environment.
